### ISSUE TITLE
Debugging in the PythonApp module

### ISSUE THREAD

**Issue by ericrcole** [neurotechcenter/BCpy2000#4]
Hi everyone,

I haven't found any info on this, so forgive me if I missed it. The description for BCPy2000 on the BCI2000 wiki page says it is compatible with iPython for debugging, but what is the right code & syntax to use iPython in the PythonApp module? I've tried a few different things, but they all seem to give me the same error. For example, I tried using two methods (one is commented):  

```
def Transition(self, phase):
		import ipdb; ipdb.set_trace()
#from IPython import embed; embed()

		# record what's going 
		self.states['BaselineOn'] = int(phase in ['baseline'])
		self.states['StartCueOn'] = int(phase in ['startcue'])
		self.states['StopCueOn']  = int(phase in ['stopcue'])
		self.states['Learn']      = int(phase in ['baseline', 'imagine2']) # the signal-processing module will know to learn during these two phases
		self.states['FeedbackOn'] = int(phase in ['imagine1', 'imagine2', 'imagine3'])
```
		
But they both lead to the same error:

2022-07-11T21:44:37 - Application error, PythonAppFilter::Process:
End user error: 1 0.
2022-07-11T21:44:37 - Application error, PythonAppFilter::Process:
BCI2000 must be restarted: Python error during _ProcessReport: RuntimeError: input(): lost sys.stdin: RuntimeError: input(): lost sys.stdin.
2022-07-11T21:44:37 - Application error:
Lost connection to Application.

Even knowing the best way to open a console and print outputs would be very helpful. Right now, what I want to do is be able to see the type/format and get/set state and parameter variables, but this would be very useful in general. Thanks!

**Comment by ericrcole** [comment]
I've realized I can get around this issue by using the logging package to write to a log file instead of printing to the console. However, any other recommendations would still be appreciated!

**Comment by nicklczk** [comment]
Currently we havn't updated the iPython integrated shell, so the only way to debug is through printing to the console or by writing things to a file. We're looking at possible alternative to iPython right now, but that feature is still in the works.
